server:
  port: 8082
spring:
  application:
    name: task-manager



  datasource: # ?????????? ? ???? ????????? ??????????? ? ??
    url: jdbc:postgresql://localhost:5432/tasks-db
    username: admin # ??? ????????????
    password: secret # ??????
    driver-class-name: org.postgresql.Driver # ????? jdbc ????????
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # ?????????? SQL-??????? ? ???????
    properties:
      hibernate:
        format_sql: true # ????????????? SQL ??? ??????????
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    root: INFO
    org.springframework.security: INFO
    ru.erikaMit.TaskManager: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO

